### ISSUE TITLE
website without login

### ISSUE THREAD

**Issue by nunziofiore** [fbsamples/web-friend-smash#11]
Hi 
 I saw it: https://friendsmashsample.herokuapp.com/
But I don't understand. Is possibile to include a facebook login button ? How do you set a link between your user session and facebook session?

**Comment by shir0i84** [comment]
Hi there, Friend Smash can be launched from Facebook via https://apps.facebook.com/friendsmashsample/.

To initiate the login from your code, please check out the JS quick start guide in the following link: https://developers.facebook.com/docs/javascript/quickstart/v2.5

**Comment by nunziofiore** [comment]
thank you @shir0i84  . But it's not possibile to have a website?
It's mandatory to have canvas app on desktop and mobile app in mobile devices? 
If I could use all the friendsmash features in a website and not only on canvas, people can access also from mobile and I can show it in their mobile browser without a mobile app.
