### ISSUE TITLE
on mobile 

### ISSUE THREAD

**Issue by nunziofiore** [fbsamples/web-friend-smash#12]
When you share a post from link on top left, you have a post that in facebook mobile is linked to candy crush saga and not to friendsmash

**Comment by skoggkatt** [comment]
Thank you for reporting it @nunziofiore. As Friend Smash! is a sample app it is not in the mobile app stores, as we want to encourage developers to build the project themselves on mobile platforms. Also we do not want to confuse people discovering the app organically that Facebook released a mobile game.
Of course, linking to a third party app was a bug. We fixed it now and the post will point to Facebook App instead.
