### ISSUE TITLE
Does the game work on m.facebook.com?

### ISSUE THREAD

**Issue by wzup** [fbsamples/web-friend-smash#13]
It is not clear form README if the game works on `m.facebook.com`. I tried to find the game on `m.facebook.com`, but it was in vain, there is no such a game. Try it yourself 
[https://m.facebook.com/search/?search=Search&search_source=search_bar&query=friend%20smash!](https://m.facebook.com/search/?search=Search&search_source=search_bar&query=friend%20smash!)

Also when I tried to run [http://apps.facebook.com/friendsmashsample](http://apps.facebook.com/friendsmashsample) from a smart phone, I got pure desktop version of FB and the game. It was not `m.apps.facebook.com/friendsmashsample`.

My question is. 
FB has web mobile version `m.facebook.com`. Do all those games that FB promotes as [game directly on Facebook.com on desktops and laptops](https://developers.facebook.com/docs/games/gamesonfacebook) have `m.facebook.com` version? How to develop games for `m.facebook.com`? Is there any significant difference from developing for plain old `facebook.com`?

**Comment by skoggkatt** [comment]
The games platform does not exist on m.facebook.com and to answer your question - you cannot develop games for m.facebook.com. 
For more info on developing on mobile with native Facebook SDKs check [Mobile Games](https://developers.facebook.com/docs/games/mobile) section of the developer documentation and Friend Smash! samples for [iOS](https://github.com/fbsamples/ios-friend-smash), [Android](https://github.com/fbsamples/android-friend-smash) and [Unity](https://github.com/fbsamples/friendsmash-unity)
