### ISSUE TITLE
friendsmashsample fb app link is dead

### ISSUE THREAD

**Issue by nvcken** [fbsamples/web-friend-smash#14]
https://apps.facebook.com/friendsmashsample/

**Comment by skoggkatt** [comment]
@nvcken can you provide more details what's broken? 
the link seems to be working fine on all browsers I've tried.

**Comment by nvcken** [comment]
aaah, seem my ISP blocks apps.facebook.com

**Comment by edudemy** [comment]
@skoggkatt https://apps.facebook.com/friendsmashsample/ is indeed is broken now. Anything changed post the update?  The projects and demo seem silent.
