### ISSUE TITLE
graph_api.js

### ISSUE THREAD

**Issue by 3dmasons** [fbsamples/web-friend-smash#15]
The "index.php" source has a script source searching for "scripts/integration/graph_api.js" but it does not exist. Is this no longer needed? I was hoping to find more example code even if that script is no longer needed.

**Comment by shir0i84** [comment]
Hi there, the script source for "graph_api.js" was merged into other files, like "sharing.js" and "login.js". Do you have any specific example that you are looking for? We have more Javascript examples here: https://developers.facebook.com/docs/javascript/examples
