### ISSUE TITLE
Developer Source code & Documentation  : Payments in friend smash tutorial V2

### ISSUE THREAD

**Issue by edudemy** [fbsamples/web-friend-smash#2]
Hi @aliparr & FB Team,

I checked out the v2 of friend smash social & noticed the non-requirement of a (php) server. Any static file server capable of accepting POST requests on static files seems to be able to host the facebook app.  Is this a design decision for v2?

1) How does it ensure security of OAuth tokens (tokens thus generated seem to be short lived with around 4800s duration), since no server side is involved?

2) How to implement persistence & payments in V2 of friend smash social?

Kindly refer to any existing documentation  for the above? 
The canvas game tutorial under developer docs does not offer any information on payments implementation. 

Can we just port the corresponding payments related files from [v1](https://github.com/fbsamples/web-friend-smash-v1) to v2 and expect it to work, without modification (ie additional server side php code)?
https://developers.facebook.com/docs/games/canvas/canvas-tutorial

TIA for any pointers.

**Comment by connortreacy** [comment]
Hi @edudemy, we elected not to ship the tutorial as-is, instead preferring to ship clear annotated code. If you look in the /payments folder in the latest version of this repo, you'll see the server-side code we're using for handling payments. It's deliberately basic, but should give you an idea of how to handle payment validation. 

In this version of the sample app, we're referencing external Parse and Facebook sdks, both on different platforms, so there's no concern about XDM here.

Feel free to open another issue if you feel your questions weren't fully addressed, and thanks again for the feedback!
